# Generated by Django 5.2 on 2025-04-06 22:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.CharField(max_length=255)),
                ('processed_image', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=100)),
                ('filter_applied', models.CharField(choices=[('gray', 'Grayscale'), ('sepia', 'Sepia'), ('poster', 'Poster'), ('blur', 'Blur'), ('edge', 'Edge Detection'), ('solar', 'Solarize')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
